"""!
@file crawl_config_test.py
@brief Tests for the shared skip list in agent/crawl_config.py.
@details T-139: eShopOnWeb's wwwroot (jQuery, Bootstrap) and Migrations
(generated by Entity Framework) were summarized as if a person wrote them.
"""

import os

from agent.crawl_config import prune


def test_prune_skips_web_libraries_and_migrations(tmp_path):
    dirs = ["wwwroot", "Migrations", "Pages", "Services", "bin"]

    prune(str(tmp_path), dirs)

    assert dirs == ["Pages", "Services"]


def test_walk_never_enters_skipped_folders(tmp_path):
    for folder in ("src/Web/wwwroot/lib/jquery", "src/Infrastructure/Data/Migrations", "src/Web/Pages"):
        (tmp_path / folder).mkdir(parents=True)
        (tmp_path / folder / "file.cs").write_text("// code", encoding="utf-8")

    seen = []
    for root, dirs, files in os.walk(tmp_path):
        prune(root, dirs)
        seen += [os.path.relpath(os.path.join(root, f), tmp_path).replace(os.sep, "/") for f in files]

    assert seen == ["src/Web/Pages/file.cs"]
