"""
agent/crawl_config.py

Shared rules for which files and folders the pipeline looks at.

These used to be local variables inside two different crawler functions:
IGNORED_DIRS in directory_agent.crawler_node, and acceptable_extensions in
file_summary_agent.crawler_node. Only the directory crawler had a skip list,
so the file crawler walked into bin/, obj/, node_modules/ and .venv/ and paid
for one LLM call per generated or vendored file.

Keeping both lists here means the crawlers, and the token estimator that
predicts their cost, cannot disagree about what counts as source code.
"""

import os

# File types the pipeline will summarize.
ACCEPTABLE_EXTENSIONS = {
    ".cs", ".py", ".md", ".js", ".ts",
    ".sh", ".bash", ".c", ".cpp", ".html", ".css",
}

# Folders that hold generated, vendored or tooling files rather than code a
# person wrote. May need extending as more target languages are supported.
IGNORED_DIRS = {
    ".git",
    ".github",
    "__pycache__",
    "node_modules",
    "bin",
    "obj",
    ".venv",
    ".vscode",
    "NuSpecs",
    "NuSpec",
    "Debug",
    # ASP.NET: downloaded web libraries (jQuery, Bootstrap) and the database
    # migrations Entity Framework generates.
    "wwwroot",
    "Migrations",
}


# Checkpoint writes its generated test project inside the codebase it is
# analysing. Without this marker the next run crawls those tests as if a
# person wrote them. A name rule like "*.Tests" would also skip a project's
# own hand-written tests, so the folder is tagged instead.
GENERATED_MARKER = ".checkpoint-generated"


def mark_generated(path):
    """
    Tag a folder Checkpoint created so prune() skips it on later runs.

    Does nothing if the folder does not exist, e.g. when `dotnet new` failed.
    """
    if os.path.isdir(path):
        with open(os.path.join(path, GENERATED_MARKER), "w", encoding="utf-8") as f:
            f.write("Generated by Checkpoint. Excluded from analysis.\n")


def prune(root, dirs):
    """
    Drop ignored and Checkpoint-generated folders from an os.walk
    subdirectory list, in place.

    os.walk only skips a folder if its `dirs` list is mutated in place before
    the next iteration -- rebinding the name does nothing. Call as:

        for root, dirs, filenames in os.walk(path):
            prune(root, dirs)
    """
    dirs[:] = [
        d for d in dirs
        if d not in IGNORED_DIRS
        and not os.path.exists(os.path.join(root, d, GENERATED_MARKER))
    ]
    return dirs
