"""
@file build_database_JSON.py
@brief Core script for indexing a codebase into a ChromaDB vector store.
@details This script performs the ETL (Extract, Transform, Load) process for structured
LLM-generated summaries. It reads JSON files from a specified directory, flattens the
hierarchical data (files, types, methods, properties, and relationships), and upserts
them as searchable embeddings into a persistent ChromaDB collection.
"""
import logging
logger = logging.getLogger(__name__)
import json
import sys
from pathlib import Path

import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

from backend.progress_logging import progress
from utils.chroma_utils import collection_name as build_collection_name


def format_parameters(parameters: list[dict] | None) -> str:
    """
    @brief Formats a parameter list into a readable string.
    """
    if not parameters:
        return "None"

    formatted = []
    for param in parameters:
        direction = param.get("direction", "in")
        name = param.get("name", "unknown")
        ptype = param.get("type") or "unknown"
        formatted.append(f"{direction} {name}: {ptype}")
    return ", ".join(formatted)


def build_database(codebase_name: str) -> None:
    """
    @brief Assembles a local ChromaDB database from a directory of JSON files.

    @details
    This function:
    1. Locates the JSON summaries generated by the FileSummaryAgent.
    2. Initializes a persistent ChromaDB client and embedding function.
    3. Flattens the nested JSON structure into unique vector nodes for:
       - File-level summaries
       - Top-level functions
       - Types (class / enum / interface / struct)
       - Type methods
       - Type properties
       - File relationships
    4. Performs an upsert operation to the database to ensure no duplicate entries
       exist within the specific collection.

    @param codebase_name str: The name of the codebase folder to index.
    @return None
    """
    if getattr(sys, 'frozen', False):
        base_dir = Path(sys.executable).parent
    else:
        base_dir = Path(__file__).parent.parent

    json_dir = (base_dir / "agent" / "file_summary_agent_output" / codebase_name).resolve()
    db_dir = (base_dir / "vectorStores").resolve()

    progress(
        f"Preparing summary database for {codebase_name}...",
        percent=5
    )

    if not json_dir.exists() or not json_dir.is_dir():
        logger.error(f"Error: The provided JSON directory '{json_dir}' does not exist or is not a directory.")
        sys.exit(1)

    client = chromadb.PersistentClient(path=str(db_dir))

    progress(
        "Loading embedding model...",
        percent=15
    )

    embedding_fn = SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )

    progress(
        "Embedding model loaded",
        percent=25
    )

    collection_name = build_collection_name(codebase_name, "summary")
    logger.info(f"\n--- Building Collection: {collection_name} ---")
    collection = client.get_or_create_collection(
        name=collection_name,
        embedding_function=embedding_fn
    )

    progress(
        "Initialized summary vector collection",
        percent=30
    )

    ids: list[str] = []
    documents: list[str] = []
    metadatas: list[dict] = []
    seen_ids: set[str] = set()

    json_files = sorted(json_dir.glob("*.json"))

    progress(
        f"Processing {len(json_files)} summary files...",
        percent=35
    )


    for index, file_path in enumerate(json_files, start=1):

        file_progress = 35 + int(
            (index / len(json_files)) * 35
        )

        progress(
            f"Indexing summary {index}/{len(json_files)}: {file_path.name}",
            percent=file_progress
        )

        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        src_path = data.get("path", "unknown")
        summary = data.get("summary", "")
        dependencies = data.get("dependencies") or []
        functions = data.get("functions") or []
        types = data.get("types") or []
        relationships = data.get("relationships") or []
        external_relationships = data.get("external_relationships") or []
        relationship_plantuml = data.get("relationship_plantuml", "")

        # 1. File-level node
        f_id = f"file:{src_path}"
        if f_id not in seen_ids:
            seen_ids.add(f_id)
            ids.append(f_id)
            documents.append(
                f"File Path: {src_path}\n"
                f"Global Summary: {summary}\n"
                f"Dependencies: {', '.join(dependencies) if dependencies else 'None'}\n"
                f"Number of top-level functions: {len(functions)}\n"
                f"Number of types: {len(types)}\n"
                f"Number of in-file relationships: {len(relationships)}\n"
                f"Number of external relationships: {len(external_relationships)}\n"
                f"Relationship PlantUML:\n{relationship_plantuml}"
            )
            metadatas.append({
                "type": "file",
                "path": src_path,
            })

        # 2. Top-level functions
        for func in functions:
            name = func.get("name", "unknown")
            description = func.get("description", "")
            return_type = func.get("return_type") or "None"
            parameters = format_parameters(func.get("parameters"))
            calls = ", ".join(func.get("calls") or []) or "None"
            visibility = func.get("visibility") or "unknown"

            func_id = f"func:{src_path}:{name}"
            if func_id not in seen_ids:
                seen_ids.add(func_id)
                ids.append(func_id)
                documents.append(
                    f"Top-level function '{name}' in {src_path}.\n"
                    f"Description: {description}\n"
                    f"Visibility: {visibility}\n"
                    f"Return type: {return_type}\n"
                    f"Parameters: {parameters}\n"
                    f"Calls: {calls}"
                )
                metadatas.append({
                    "type": "function",
                    "name": name,
                    "path": src_path,
                })

        # 3. Types (class / enum / interface / struct)
        for type_obj in types:
            type_name = type_obj.get("name", "unknown")
            type_kind = type_obj.get("kind", "unknown")
            type_description = type_obj.get("description", "")
            inherits_from = ", ".join(type_obj.get("inherits_from") or []) or "None"
            enum_values = ", ".join(type_obj.get("enum_values") or []) or "None"
            plantuml = type_obj.get("plantuml", "")
            properties = type_obj.get("properties") or []
            methods = type_obj.get("methods") or []

            type_id = f"type:{src_path}:{type_kind}:{type_name}"
            if type_id not in seen_ids:
                seen_ids.add(type_id)
                ids.append(type_id)
                documents.append(
                    f"Type '{type_name}' ({type_kind}) in {src_path}.\n"
                    f"Description: {type_description}\n"
                    f"Inherits from: {inherits_from}\n"
                    f"Enum values: {enum_values}\n"
                    f"Properties count: {len(properties)}\n"
                    f"Methods count: {len(methods)}\n"
                    f"PlantUML:\n{plantuml}"
                )
                metadatas.append({
                    "type": "type",
                    "name": type_name,
                    "kind": type_kind,
                    "path": src_path,
                })

            # 4. Type properties
            for prop in properties:
                prop_name = prop.get("name", "unknown")
                prop_type = prop.get("type") or "unknown"
                prop_description = prop.get("description", "")
                prop_visibility = prop.get("visibility") or "unknown"
                prop_static = prop.get("is_static", False)

                prop_id = f"property:{src_path}:{type_name}:{prop_name}"
                if prop_id not in seen_ids:
                    seen_ids.add(prop_id)
                    ids.append(prop_id)
                    documents.append(
                        f"Property '{prop_name}' belonging to {type_kind} '{type_name}' in {src_path}.\n"
                        f"Description: {prop_description}\n"
                        f"Type: {prop_type}\n"
                        f"Visibility: {prop_visibility}\n"
                        f"Static: {prop_static}"
                    )
                    metadatas.append({
                        "type": "property",
                        "name": prop_name,
                        "parent": type_name,
                        "parent_kind": type_kind,
                        "path": src_path,
                    })

            # 5. Type methods / constructors
            for method in methods:
                method_name = method.get("name", "unknown")
                method_description = method.get("description", "")
                method_visibility = method.get("visibility") or "unknown"
                method_return_type = method.get("return_type") or "None"
                method_parameters = format_parameters(method.get("parameters"))
                is_static = method.get("is_static", False)
                is_constructor = method.get("is_constructor", False)

                method_id = f"method:{src_path}:{type_name}:{method_name}"
                if method_id not in seen_ids:
                    seen_ids.add(method_id)
                    ids.append(method_id)
                    documents.append(
                        f"Method '{method_name}' belonging to {type_kind} '{type_name}' in {src_path}.\n"
                        f"Description: {method_description}\n"
                        f"Visibility: {method_visibility}\n"
                        f"Return type: {method_return_type}\n"
                        f"Parameters: {method_parameters}\n"
                        f"Static: {is_static}\n"
                        f"Constructor: {is_constructor}"
                    )
                    metadatas.append({
                        "type": "method",
                        "name": method_name,
                        "parent": type_name,
                        "parent_kind": type_kind,
                        "path": src_path,
                    })

        # 6. Relationships
        for rel in relationships:
            source = rel.get("source", "unknown")
            target = rel.get("target", "unknown")
            rel_type = rel.get("relationship_type", "unknown")

            rel_id = f"relationship:{src_path}:{source}:{rel_type}:{target}"
            if rel_id not in seen_ids:
                seen_ids.add(rel_id)
                ids.append(rel_id)
                documents.append(
                    f"In-file relationship in {src_path}: "
                    f"{source} {rel_type} {target}."
                )
                metadatas.append({
                    "type": "relationship",
                    "source": source,
                    "target": target,
                    "relationship_type": rel_type,
                    "path": src_path,
                })

        # 7. External relationships
        for rel in external_relationships:
            source = rel.get("source", "unknown")
            target = rel.get("target", "unknown")
            rel_type = rel.get("relationship_type", "unknown")

            rel_id = f"external_relationship:{src_path}:{source}:{rel_type}:{target}"
            if rel_id not in seen_ids:
                seen_ids.add(rel_id)
                ids.append(rel_id)
                documents.append(
                    f"External relationship in {src_path}: "
                    f"{source} {rel_type} external type {target}."
                )
                metadatas.append({
                    "type": "external_relationship",
                    "source": source,
                    "target": target,
                    "relationship_type": rel_type,
                    "path": src_path,
                })

    

    if ids:
        progress(
            f"Uploading {len(ids)} summary embeddings...",
            percent=80
        )
        collection.upsert(ids=ids, documents=documents, metadatas=metadatas)
        progress(
            f"Finished indexing {len(ids)} summary items",
            percent=100,
            step_complete=True
        )

        logger.info(
            f"Finished indexing {len(ids)} unique items for {codebase_name}"
        )
    else:
        progress(
            "No JSON summaries found",
            percent=100,
            step_complete=True
        )

        logger.info(
            f"No JSON summaries found to index for {codebase_name}."
        )


if __name__ == "__main__":
    """
    @brief Script entry point for the summary database builder.
    @details Validates command line arguments and initiates the indexing process.
    """
    if len(sys.argv) != 2:
        logger.info("Usage: python build_database_JSON.py <codebase_name>")
        sys.exit(1)

    build_database(sys.argv[1])